### ISSUE TITLE
Error on line 1, column 7: "name" field doesn't match expected name "hotkey_manager".   ╷ 1 │ name: hotkey_manager_workspace

### ISSUE THREAD

**Issue by luohao123** [leanflutter/hotkey_manager#47]
Error on line 1, column 7: "name" field doesn't match expected name "hotkey_manager".
  ╷
1 │ name: hotkey_manager_workspace

**Comment by lijy91** [comment]
Now that it has been converted to a federated plugin, please note its project structure

**Comment by lijy91** [comment]
```
dependencies:
  hotkey_manager:
    git:
      path: packages/hotkey_manager
      url: https://github.com/leanflutter/hotkey_manager.git
      ref: main
```
